### ISSUE TITLE
Frame from previous recording stuck in buffer.

### ISSUE THREAD

**Issue by itzaks** [jvcleave/ofxOMXRecorder#7]
I'm fiddling around with doing multiple recordings, and I find that often times a frame from the previous recording gets stuck in the loop. Any ideas what could cause this? I'm quite new in this area but I'm happy to dive in if you have any pointers!

Thanks :)

**Comment by jvcleave** [comment]
hard to say without seeing the implementation. if you are using the same pixels maybe try clearing them inbetween recordings

**Comment by itzaks** [comment]
Ah yes, I do. That must be it then, thanks!
